spring:
  application:
    name: 'users'
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka