spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka